networks:
  invest-net:
    driver: bridge
    name: invest-net

volumes:
  postgres_data:
    name: invest_postgres_data
  kafka_data:
    name: invest_kafka_data
  # O grafana_data foi removido daqui propositalmente. 
  # Agora ele é uma pasta física gerenciada por você, não pelo Docker.

services:
  # 1. Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: invest-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: investimentos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invest-net

  # 1.1 Exporter do Banco (O espião de métricas)
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: invest-postgres-exporter
    restart: unless-stopped
    environment:
      # Conecta no container 'invest-db' usando a rede interna
      DATA_SOURCE_NAME: "postgresql://admin:admin@invest-db:5432/investimentos?sslmode=disable"
    networks:
      - invest-net
    depends_on:
      - postgres

  # 2. Mensageria Oficial
  kafka:
    image: apache/kafka:3.7.0
    container_name: invest-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - invest-net

  # 3. Motor de Monitoramento
  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: invest-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - invest-net

  # 4. Tela do SRE
  grafana:
    image: grafana/grafana-oss:10.4.1
    container_name: invest-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      # A MÁGICA SRE AQUI: O ./ diz ao Docker para criar a pasta física
      - ./grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - invest-net